services:
  frontend:
    build:
      context: ./synceditor
      dockerfile: Dockerfile
    image: sync-frontend
    container_name: sync-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    image: sync-server
    container_name: sync-server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
